name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.85.0

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Install toolchain
        uses: https://github.com/dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt
      - name: Check
        run: cargo check --all
      - name: Formatting
        run: cargo fmt --all --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Install toolchain
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Test
        run: cargo test --all-features --all-targets

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Install toolchain
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy
      - name: Lint
        run: cargo clippy --all-features --all-targets -- -D warnings

  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Install toolchain
        uses: https://github.com/dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
      - name: Install cargo-binstall
        uses: https://github.com/cargo-bins/cargo-binstall@main
      - name: Semver compatibility
        run: cargo binstall cargo-semver-checks && cargo +nightly semver-checks
