name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  MSRV: 1.85.0

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v5
      - name: Install toolchain
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.MSRV }}
          components: rustfmt, clippy
      - name: Check
        run: cargo check --all-features --all-targets
      - name: Formatting
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v5
      - name: Install toolchain
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.MSRV }}
      - name: Tests
        run: cargo test --all-features --all-targets

  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v5
      - name: Install toolchain
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install cargo-binstall
        uses: https://github.com/cargo-bins/cargo-binstall@main
      - name: Semver compatibility
        run: cargo binstall cargo-semver-checks && cargo +stable semver-checks
